#!/usr/bin/perl

use HTML::Parser ();

# Create parser object
$p = HTML::Parser->new( api_version => 3,
                        start_h => [\&start, "tagname, attr"],
                        end_h   => [\&end,   "tagname"],
                        marked_sections => 1,
                      );

$filename = "app?service=page&page=gamestats&fetchKey=20092ALLAATAll&viewName=gameSummary&sort=game.gameDate&pg=1";
$p->parse_file("../data/$filename");
