#!/usr/bin/perl
#
# Program to do the obvious
#
#$s = 'hello world';
#print "$s\n";		# Print a message
#@letters = ("aye", "bee", "cee");
#print @letters.'\n';

#$file = '/etc/passwd';		# Name the file
#open(INFO, $file);		# Open the file
#@lines = <INFO>;		# Read it into an array
#close(INFO);			# Close the file
#print @lines;			# Print the array

$url = 'www.nhl.com/';
$remotePath = 'nhlstats/'; 
$pageBase = 'app?service=page\&page=Stats\&fetchKey=20082XXXAATAll\&viewName=gameSummary\&sort=game.gameDate\&pg=';
$localDir = 'data';
@nhlTeams = ('ANA', 'ATL');
foreach $team (@nhlTeams){
    for (my $i = 1; $i < 4;  ++$i){
        $page = $pageBase;
        $page =~ s/XXX/$team/;
        system "wget $url$remotePath$page$i -P $localDir";
    }
}

$file = $localDir.'/'.$page.'1';
$file =~ s/\\//g;

open(htmlFile, $file);
@fileLines = <htmlFile>;
close(htmlFile);
$inTR = 0;
foreach $line (@fileLines){
    if ($line =~ /<tr /){
        $inTR = 1;
        @tableLine = ();
    }
    elsif ($line =~ /<\/tr>/){
        if (@tableLine >= 9 && ($tableLine[4] eq 'H' || $tableLine[4] eq 'R')){
            if ($tableLine[4] =~ 'H'){ 
                $homeTeam = $tableLine[1];
                $awayTeam = $tableLine[5];
                $homeGoals = $tableLine[7];
                $awayGoals = $tableLine[8];
            }
            else{
                $homeTeam = $tableLine[5];
                $awayTeam = $tableLine[1];
                $homeGoals = $tableLine[8];
                $awayGoals = $tableLine[7];
            }
            $gameDate = $tableLine[0];
            $gameDate =~ s/(\S+)\s(\S+)\s'(\S+)/$1-$2-20$3/;
            @tableLine = ();
            print "$gameDate, $homeTeam, $awayTeam, $homeGoals, $awayGoals\n";
        }
        $inTR = 0;
    }
    if ($inTR && $line =~ /<td /){
        $line =~ s/^\s*//g;
        $line =~ s/<.*?>//g;
        chop $line;
        push(@tableLine, $line);
    }
}
